In [9]:
## Go back to the brief, make sure everything is ticked off
## It's why WHY that's important. Why by expirimentation and/or referencing. 
# Why boxplot, why colours, why titles, etc. etc. in the report (for David, 200-300 words) in the markdown for sam. Sam only read the notebook I think.  
## There's a template for CA3 
 # Intro, main body, conclusion 
# Resources on Student Success 
# See Research papers on David's Moodle page as samples for structure
# Go back to the feedback form CA1

In [12]:
# Fix Github to Public

In [14]:
#  Reading - what impacts the price of wheat 
# https://www.ers.usda.gov/webdocs/publications/47264/51088_tb1878b.pdf?v=0 
## https://www.economicshelp.org/blog/168151/economics/factors-determining-the-price-of-wheat/#:~:text=The%20price%20of%20wheat%20is,climate%20factors%20affecting%20the%20supply.

In [10]:

import pandas as pd
import matplotlib as mpl
import numpy as np

In [178]:
# Import all economic datasets


df1 = pd.read_csv("DATA/DP_LIVE_06012023190448991.csv")
df2 = pd.read_csv("DATA/DP_LIVE_06012023190508679.csv")
df3 = pd.read_csv("DATA/DP_LIVE_06012023190521038.csv")
df4 = pd.read_csv("DATA/DP_LIVE_06012023190621335.csv")
df5 = pd.read_csv("DATA/DP_LIVE_06012023190631007.csv")
df6 = pd.read_csv("DATA/DP_LIVE_06012023190759570.csv")
df7 = pd.read_csv("DATA/DP_LIVE_06012023190909741.csv")
df8 = pd.read_csv("DATA/DP_LIVE_06012023191011288.csv")
df9 = pd.read_csv("DATA/DP_LIVE_06012023191646976.csv")
df10 = pd.read_csv("DATA/DP_LIVE_06012023192018179.csv")
df11 = pd.read_csv("DATA/DP_LIVE_06012023192105335.csv")
df12 = pd.read_csv("DATA/DP_LIVE_06012023214944235.csv")
df13 = pd.read_csv("DATA/DP_LIVE_06012023215221798.csv")
df14 = pd.read_csv("DATA/PPP-EU.csv")

In [141]:
# Monthly = df1 (CCI), df2 (CLI) , df3 (CLI)

In [194]:
# Quarterly = df11 (HHI)

In [136]:
# Annually = df4 (GDP), df5 (GDP), df6 (GFCFSector), df7 (cropyield), df8, (aggsupp), df9 (exch), df10 (GNI), df11, (grossAJD), df 12 (YRLIFELOST), df13 (oilprod), df14 (ppp)

In [193]:
df11.tail(50)

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
3021,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2010-Q1,0.20,NaN
3022,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2010-Q2,0.68,NaN
3023,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2010-Q3,0.52,NaN
3024,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2010-Q4,0.12,NaN
3025,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2011-Q1,0.36,NaN
3026,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2011-Q2,0.02,NaN
3027,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2011-Q3,0.13,NaN
3028,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2011-Q4,-0.09,NaN
3029,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2012-Q1,0.74,NaN
3030,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2012-Q2,0.14,NaN
3031,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2012-Q3,-0.21,NaN
3032,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2012-Q4,0.92,NaN
3033,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2013-Q1,-0.64,NaN
3034,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2013-Q2,0.65,NaN
3035,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2013-Q3,0.38,NaN
3036,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2013-Q4,0.05,NaN
3037,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2014-Q1,0.40,NaN
3038,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2014-Q2,0.62,NaN
3039,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2014-Q3,0.73,NaN
3040,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2014-Q4,0.84,NaN
3041,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2015-Q1,0.87,NaN
3042,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2015-Q2,0.28,NaN
3043,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2015-Q3,0.51,NaN
3044,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2015-Q4,0.35,NaN
3045,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2016-Q1,0.61,NaN
3046,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2016-Q2,0.08,NaN
3047,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2016-Q3,0.22,NaN
3048,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2016-Q4,0.46,NaN
3049,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2017-Q1,0.38,NaN
3050,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2017-Q2,0.89,NaN
3051,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2017-Q3,0.49,NaN
3052,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2017-Q4,0.39,NaN
3053,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2018-Q1,0.59,NaN
3054,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2018-Q2,0.31,NaN
3055,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2018-Q3,0.43,NaN
3056,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2018-Q4,0.56,NaN
3057,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2019-Q1,0.85,NaN
3058,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2019-Q2,0.28,NaN
3059,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2019-Q3,0.48,NaN
3060,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2019-Q4,0.36,NaN
3061,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2020-Q1,0.24,NaN
3062,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2020-Q2,3.72,NaN
3063,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2020-Q3,-0.22,NaN
3064,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2020-Q4,-1.06,NaN
3065,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2021-Q1,5.09,NaN
3066,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2021-Q2,-3.51,NaN
3067,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2021-Q3,-0.03,NaN
3068,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2021-Q4,-0.29,NaN
3069,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2022-Q1,-1.15,NaN
3070,OECD,HHDI,GROSS,PC_CHGPPCAP,Q,2022-Q2,-0.51,NaN

In [195]:
# Combine to make master economic set. As all in the same format, we can stack the DataFrames on top of each other
df_econ = pd.concat([df4, df5, df6, df7, df8, df9, df10, df12, df13], axis=0)

In [196]:
df_econ.describe()

               TIME         Value
count  33379.000000  3.337900e+04
mean    2008.754247  1.401094e+04
std       10.735205  6.024846e+04
min     1986.000000 -2.635270e+05
25%     2000.000000  2.034000e+00
50%     2009.000000  7.361200e+01
75%     2017.000000  4.776456e+03
max     2030.000000  1.312195e+06

In [199]:
df_econ.head(50)

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,AUT,GDP,TOT,USD_CAP,A,2018,56956.110562,NaN
1,AUT,GDP,TOT,USD_CAP,A,2019,59719.331647,NaN
2,AUT,GDP,TOT,USD_CAP,A,2020,57253.300563,NaN
3,AUT,GDP,TOT,USD_CAP,A,2021,59976.264665,NaN
4,BEL,GDP,TOT,USD_CAP,A,2018,52530.841510,NaN
5,BEL,GDP,TOT,USD_CAP,A,2019,55800.825988,NaN
6,BEL,GDP,TOT,USD_CAP,A,2020,54539.032525,P
7,BEL,GDP,TOT,USD_CAP,A,2021,58816.266983,P
8,CAN,GDP,TOT,USD_CAP,A,2018,49992.811418,NaN
9,CAN,GDP,TOT,USD_CAP,A,2019,49832.297981,NaN
10,CAN,GDP,TOT,USD_CAP,A,2020,47228.372488,NaN
11,CAN,GDP,TOT,USD_CAP,A,2021,53074.088264,NaN
12,CZE,GDP,TOT,USD_CAP,A,2018,41157.370409,NaN
13,CZE,GDP,TOT,USD_CAP,A,2019,44223.088155,NaN
14,CZE,GDP,TOT,USD_CAP,A,2020,42813.741340,NaN
15,CZE,GDP,TOT,USD_CAP,A,2021,44799.547333,NaN
16,DNK,GDP,TOT,USD_CAP,A,2018,57479.350221,NaN
17,DNK,GDP,TOT,USD_CAP,A,2019,59883.836280,NaN
18,DNK,GDP,TOT,USD_CAP,A,2020,60840.940164,NaN
19,DNK,GDP,TOT,USD_CAP,A,2021,64897.769113,NaN
20,FIN,GDP,TOT,USD_CAP,A,2018,49573.255773,NaN
21,FIN,GDP,TOT,USD_CAP,A,2019,51811.356163,NaN
22,FIN,GDP,TOT,USD_CAP,A,2020,52290.401497,NaN
23,FIN,GDP,TOT,USD_CAP,A,2021,54856.553847,NaN
24,FRA,GDP,TOT,USD_CAP,A,2018,46336.933985,NaN
25,FRA,GDP,TOT,USD_CAP,A,2019,50221.997111,P
26,FRA,GDP,TOT,USD_CAP,A,2020,47823.919578,P
27,FRA,GDP,TOT,USD_CAP,A,2021,50998.933198,P
28,DEU,GDP,TOT,USD_CAP,A,2018,55195.722049,NaN
29,DEU,GDP,TOT,USD_CAP,A,2019,57397.204591,P
30,DEU,GDP,TOT,USD_CAP,A,2020,56476.934309,P
31,DEU,GDP,TOT,USD_CAP,A,2021,58784.138861,P
32,GRC,GDP,TOT,USD_CAP,A,2018,29617.499309,NaN
33,GRC,GDP,TOT,USD_CAP,A,2019,31155.847016,NaN
34,GRC,GDP,TOT,USD_CAP,A,2020,28413.787339,P
35,GRC,GDP,TOT,USD_CAP,A,2021,31177.251307,P
36,HUN,GDP,TOT,USD_CAP,A,2018,31908.661917,NaN
37,HUN,GDP,TOT,USD_CAP,A,2019,34638.671964,NaN
38,HUN,GDP,TOT,USD_CAP,A,2020,34156.840044,P
39,HUN,GDP,TOT,USD_CAP,A,2021,36677.803167,P
40,IRL,GDP,TOT,USD_CAP,A,2018,84824.352993,NaN
41,IRL,GDP,TOT,USD_CAP,A,2019,89846.272208,NaN
42,IRL,GDP,TOT,USD_CAP,A,2020,94028.901163,NaN
43,IRL,GDP,TOT,USD_CAP,A,2021,106852.122229,NaN
44,ITA,GDP,TOT,USD_CAP,A,2018,43427.663143,NaN
45,ITA,GDP,TOT,USD_CAP,A,2019,45799.526931,NaN
46,ITA,GDP,TOT,USD_CAP,A,2020,43129.896677,NaN
47,ITA,GDP,TOT,USD_CAP,A,2021,46546.248219,NaN
48,JPN,GDP,TOT,USD_CAP,A,2018,42239.050068,NaN
49,JPN,GDP,TOT,USD_CAP,A,2019,42465.480080,NaN

In [200]:
df_econ.TIME.unique()

array([2018, 2019, 2020, 2021, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2022,
       2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 1986, 1987, 1988,
       1989], dtype=int64)

In [201]:
df_econ.INDICATOR.unique()

array(['GDP', 'GFCFSECTOR', 'CROPYIELD', 'AGRSUPP', 'EXCH', 'GNI',
       'YRLIFELOST', 'OILPROD'], dtype=object)

In [202]:
df_econ.SUBJECT.unique()

array(['TOT', 'GG', 'RICE', 'WHEAT', 'MAIZE', 'SOYBEAN', 'TSE', 'PSE',
       'CSE', 'GSSE'], dtype=object)

In [203]:
df_econ.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33379 entries, 0 to 683
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    33379 non-null  object
 1   INDICATOR   33379 non-null  object
 2   SUBJECT     33379 non-null  object
 3   MEASURE     33379 non-null  object
 4   FREQUENCY   33379 non-null  object
 5   TIME        33379 non-null  int64
 6   Value       33379 non-null  float64
 7   Flag Codes  197 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.3+ MB

In [204]:
# Remove dupliates 

df_econ2 = df_econ.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

In [206]:
df_econ2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33251 entries, 0 to 683
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    33251 non-null  object
 1   INDICATOR   33251 non-null  object
 2   SUBJECT     33251 non-null  object
 3   MEASURE     33251 non-null  object
 4   FREQUENCY   33251 non-null  object
 5   TIME        33251 non-null  int64
 6   Value       33251 non-null  float64
 7   Flag Codes  167 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.3+ MB

In [207]:
df_econ.LOCATION.unique()

array(['AUT', 'BEL', 'CAN', 'CZE', 'DNK', 'FIN', 'FRA', 'DEU', 'GRC',
       'HUN', 'IRL', 'ITA', 'JPN', 'LUX', 'NLD', 'POL', 'PRT', 'SVK',
       'ESP', 'SWE', 'GBR', 'USA', 'EST', 'SVN', 'OECD', 'LVA', 'LTU',
       'BGR', 'HRV', 'CYP', 'MLT', 'ROU', 'AUS', 'KOR', 'MEX', 'NZL',
       'TUR', 'ARG', 'BRA', 'CHL', 'CHN', 'COL', 'EGY', 'ETH', 'IND',
       'IDN', 'IRN', 'KAZ', 'MYS', 'NGA', 'PAK', 'PRY', 'PER', 'PHL',
       'RUS', 'SAU', 'ZAF', 'THA', 'UKR', 'VNM', 'WLD', 'BRICS', 'NOR',
       'CHE', 'ISR', 'ISL', 'EU', 'CRI'], dtype=object)

In [208]:
# Add dataset to lookup to if a country is EU  or NOT. 
df_eulookup = pd.read_csv("DATA/EU_countries.csv")

df_eulookup.head(50)

   LOCATION  EU
0       AUT   1
1       BEL   1
2       BGR   1
3       CYP   1
4       CZE   1
5       DEU   1
6       DNK   1
7       ESP   1
8       EST   1
9       FIN   1
10      FRA   1
11      GRC   1
12      HRV   1
13      HUN   1
14      IRL   1
15      ITA   1
16      LTU   1
17      LUX   1
18      LVA   1
19      MLT   1
20      NLD   1
21      POL   1
22      PRT   1
23      ROU   1
24      SVK   1
25      SVN   1
26      SWE   1

In [209]:
# Add colum to say if Location is EU country, OECD benchark or otherwise. 
df_econ3 = df_econ2.join(df_eulookup.set_index('LOCATION'), on='LOCATION')
df_econ3.tail(100)

    LOCATION INDICATOR SUBJECT MEASURE FREQUENCY  TIME  Value Flag Codes   EU
584      EST   OILPROD     TOT    KTOE         A  2008    0.0        NaN  1.0
585      EST   OILPROD     TOT    KTOE         A  2009    0.0        NaN  1.0
586      EST   OILPROD     TOT    KTOE         A  2010    0.0        NaN  1.0
587      EST   OILPROD     TOT    KTOE         A  2011    0.0        NaN  1.0
588      EST   OILPROD     TOT    KTOE         A  2012    0.0        NaN  1.0
..       ...       ...     ...     ...       ...   ...    ...        ...  ...
679      CRI   OILPROD     TOT    KTOE         A  2013    0.0        NaN  NaN
680      CRI   OILPROD     TOT    KTOE         A  2014    0.0        NaN  NaN
681      CRI   OILPROD     TOT    KTOE         A  2015    0.0        NaN  NaN
682      CRI   OILPROD     TOT    KTOE         A  2016    0.0        NaN  NaN
683      CRI   OILPROD     TOT    KTOE         A  2017    0.0        NaN  NaN

[100 rows x 9 columns]

In [210]:
df_econ3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33251 entries, 0 to 683
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LOCATION    33251 non-null  object
 1   INDICATOR   33251 non-null  object
 2   SUBJECT     33251 non-null  object
 3   MEASURE     33251 non-null  object
 4   FREQUENCY   33251 non-null  object
 5   TIME        33251 non-null  int64
 6   Value       33251 non-null  float64
 7   Flag Codes  167 non-null    object
 8   EU          2948 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 2.5+ MB

In [211]:
df_econ3.TIME.unique()

array([2018, 2019, 2020, 2021, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2022,
       2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 1986, 1987, 1988,
       1989], dtype=int64)

In [214]:
# Mask formula to remove some that contains "-" from the new df

# year_mask = (df_econ3.TIME.str.find("-")==-1)
# df_econ3_year = df_econ3[year_mask]

In [215]:
df_econ3_year

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes,EU
0,JPN,HHDI,GROSSADJ,USD_CAP,A,1994,16124.253761,NaN,NaN
1,JPN,HHDI,GROSSADJ,USD_CAP,A,1995,16737.559497,NaN,NaN
2,JPN,HHDI,GROSSADJ,USD_CAP,A,1996,17137.574301,NaN,NaN
3,JPN,HHDI,GROSSADJ,USD_CAP,A,1997,17604.818244,NaN,NaN
4,JPN,HHDI,GROSSADJ,USD_CAP,A,1998,17790.334459,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1461,OECD,HHDI,GROSS,PC_CHGPPCAP,A,2017,1.650000,NaN,NaN
1462,OECD,HHDI,GROSS,PC_CHGPPCAP,A,2018,2.010000,NaN,NaN
1463,OECD,HHDI,GROSS,PC_CHGPPCAP,A,2019,2.140000,NaN,NaN
1464,OECD,HHDI,GROSS,PC_CHGPPCAP,A,2020,3.340000,NaN,NaN
1465,OECD,HHDI,GROSS,PC_CHGPPCAP,A,2021,1.480000,NaN,NaN

In [220]:
df_econ4 = df_econ3.astype({'TIME':'int'})

In [225]:
df_econ5.TIME.unique()

array([2018, 2019, 2020, 2021, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030], dtype=int64)

In [78]:
# from pandas.core.reshape.pivot import pivot

In [89]:
pd.pivot_table(df_econ3, values = 'Value', index=['LOCATION','TIME'], columns = 'INDICATOR').reset_index()

INDICATOR,LOCATION,TIME,AGRSUPP,CCI,CLI,CROPYIELD,EXCH,GDP,GFCFSECTOR,GNI,HHDI,OILPROD,YRLIFELOST
0,ARG,1990,NaN,NaN,NaN,3592.324250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARG,1991,NaN,NaN,NaN,3685.865750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ARG,1992,NaN,NaN,NaN,3708.984667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ARG,1993,NaN,NaN,NaN,3782.307667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARG,1994,NaN,NaN,NaN,4102.401917,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10879,ZAF,2026,NaN,NaN,NaN,2143.978167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10880,ZAF,2027,NaN,NaN,NaN,2175.352500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10881,ZAF,2028,NaN,NaN,NaN,2206.567750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10882,ZAF,2029,NaN,NaN,NaN,2239.788250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10883,ZAF,2030,NaN,NaN,NaN,2275.879083,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Sample 

## Getting Started with Interactive Data Visualizations

# import pandas as pd
# import numpy as np

In [ ]:

co2 = pd.read_csv('data/co2.csv')
co2.head()

gm = pd.read_csv('data/gapminder.csv')
gm.head()

df_gm = gm[['Country', 'region']].drop_duplicates()

df_w_regions = pd.merge(co2, df_gm, left_on='country', right_on='Country', how='inner')

df_w_regions = df_w_regions.drop('Country', axis='columns')

new_co2 = pd.melt(df_w_regions, id_vars=['country', 'region'])

columns = ['country', 'region', 'year', 'co2']
new_co2.columns = columns

df_co2 = new_co2[new_co2['year'].astype('int64') > 1963]
df_co2 = df_co2.sort_values(by=['country', 'year'])
df_co2['year'] = df_co2['year'].astype('int64')
df_co2.head()

df_gdp = gm[['Country', 'Year', 'gdp']]
df_gdp.columns = ['country', 'year', 'gdp']
df_gdp.head()

data = pd.merge(df_co2, df_gdp, on=['country', 'year'], how='left')

data = data.dropna()
data.head()

np_co2 = np.array(data['co2'])
np_gdp = np.array(data['gdp'])
np.corrcoef(np_co2, np_gdp)

from bokeh.io import curdoc, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource, CategoricalColorMapper, Slider
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row

output_notebook()

regions_list = data.region.unique().tolist()
color_mapper = CategoricalColorMapper(factors=regions_list, palette=Spectral6)

Make the ColumnDataSource: source


source = ColumnDataSource(data={
    'x': data.gdp[data['year'] == 1964],
    'y': data.co2[data['year'] == 1964],
    'country': data.country[data['year'] == 1964],
    'region': data.region[data['year'] == 1964],
})

Save the minimum and maximum values of the gdp column: xmin, xmax

xmin, xmax = min(data.gdp), max(data.gdp)

Save the minimum and maximum values of the co2 column: ymin, ymax

ymin, ymax = min(data.co2), max(data.co2)

Create the figure: plot


plot = figure(title='CO2 Emissions vs GDP in 1964', 
              plot_height=600, plot_width=1000,
              x_range=(xmin, xmax),
              y_range=(ymin, ymax), y_axis_type='log')

Add circle glyphs to the plot

plot.circle(x='x', y='y', fill_alpha=0.8, source=source, legend='region',
            color=dict(field='region', transform=color_mapper),
            size=7)

# Set the legend.location attribute of the plot
plot.legend.location = 'bottom_right'

# Set the x-axis label
plot.xaxis.axis_label = 'Income Per Person'

# Set the y-axis label
plot.yaxis.axis_label = 'CO2 Emissions (tons per person)'

show(plot)

### Adding a Slider to the Static Plot 

slider = Slider(start=min(data.year), end=max(data.year), step=1,
value=min(data.year), title='Year') 

def update_plot(attr, old, new):
    yr = slider.value
    new_data = {
     'x': data.gdp[data['year'] == yr], 
     'y': data.co2[data['year'] == yr],
     'country': data.country[data['year'] == yr],
     'region': data.region[data['year'] == yr],
    }
    source.data = new_data
    plot.title.text = 'CO2 Emissions vs GDP in %d' % yr 

slider.on_change('value', update_plot)

layout = row(widgetbox(slider), plot) 

curdoc().add_root(layout) 

### Adding a Hover Tool 

hover = HoverTool(tooltips=[('Country', '@country'), ('GDP', '@x'), ('CO2 Emission','@y')]) 

plot.add_tools(hover) 

!bokeh serve --show Getting_Started_with_Interactive_Data_Visualizations.ipynb

## Interactive Data Visualization with Plotly Express 

import pandas as pd
import plotly.express as px 

co2 = pd.read_csv('data/co2.csv')
gm = pd.read_csv('data/gapminder.csv')

df_gm = gm[['Country', 'region']].drop_duplicates()
df_w_regions = pd.merge(co2, df_gm, left_on='country', right_on='Country',how='inner')
df_w_regions = df_w_regions.drop('Country', axis='columns')
new_co2 = pd.melt(df_w_regions, id_vars=['country', 'region'])
columns = ['country', 'region', 'year', 'co2']
new_co2.columns = columns
df_co2 = new_co2[new_co2['year'].astype('int64') > 1963]
df_co2 = df_co2.sort_values(by=['country', 'year'])
df_co2['year'] = df_co2['year'].astype('int64')
df_gdp = gm[['Country', 'Year', 'gdp']]
df_gdp.columns = ['country', 'year', 'gdp']
data = pd.merge(df_co2, df_gdp, on=['country', 'year'], how='left') 
data = data.dropna() 

data.head() 


xmin, xmax = min(data.gdp), max(data.gdp) 

ymin, ymax = min(data.co2), max(data.co2) 

fig = px.scatter(data, x="gdp", y="co2", animation_frame="year",
animation_group="country", color="region", hover_name="country",
facet_col="region", width=1579, height=400, log_x=True, size_max=45,
range_x=[xmin,xmax], range_y=[ymin,ymax]) 


fig.show()